develInternChallenge/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pictureApp.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pictureApp/urls.py
from django.urls import path, include
from . import views

app_name = "pictureApp"

urlpatterns = [
    path('', views.index, name="index"),
    path('index', views.index, name="index"),
    path('addMultiplePhotos', views.addMultiplePhotos, name="addMultiplePhotos"),
    path('titleMultiplePhotos', views.titleMultiplePhotos, name="titleMultiplePhotos"),
    path('persistPhoto/<_id>', views.persistPhoto, name="persistPhoto"),
    path('deletePhoto/<_id>', views.deletePhoto, name="deletePhoto"),
    path('deleteAPhoto/<_id>', views.deleteAPhoto, name="deleteAPhoto"),
    path('deleteMultiPhoto/', views.deleteMultiPhoto, name="deleteMultiPhoto"),
    path('searchPhoto/', views.searchPhoto, name="searchPhoto"),
    path('statusChange/<_id>', views.statusChange, name="statusChange"),
    path('userPrivatePhotos', views.userPrivatePhotos, name="userPrivatePhotos"),
    path('userPublicPhotos', views.userPublicPhotos, name="userPublicPhotos"),
    path('userAllPhotos', views.userAllPhotos, name="userAllPhotos"),
    path('allPublicPhotos', views.allPublicPhotos, name="allPublicPhotos"),
    path('logout', views.logout, name="logout"),
    path('login', views.login, name="login"),
]

pictureApp/models.py
from django.db import models

# Create your models here.

class Photo(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField()
    status = models.BooleanField(default=True)
    user = models.CharField(max_length=15, default="AnonymousUser")
    
    def __str__(self):
        return self.title + ' status: ' + str(self.status)

pictureApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.http import HttpResponse
from .models import *
import os 

from .form import *

# Function to delete all the pictures without title
def delNoTitle():
    obj = Photo.objects.all()
    for p in obj:
        if p.title == 'NoNameTitle':
            file_path = 'static/photosFolder/' + str(p.image)   # get file full path
            os.remove(file_path)    # delete file from local folder
            p.delete()      # delete object data from database

#Function to know SignIn or Not
def isSignIn(request):
    returning_value = True
    if "AnonymousUser" == str(request.user):
        returning_value = False
    return returning_value

#Function to get Current User's Photo and others Public Only
def currentPhoto(request):
    photoList = []
    currentUser = str(request.user)     #name of current user
    photo=Photo.objects.all()

    for p in photo:
        temp = []   # at Index 0 will store True/False and Index 1 will store photo object
        if currentUser == p.user:
            temp.append(True)   # TRUE is to show edit button
            temp.append(p)
            photoList.append(temp)
        elif p.status == False:
            temp.append(False)  # FALSE is to hide edit buttons
            temp.append(p)
            photoList.append(temp)
    photoList.reverse()

    return photoList

# Create your views here.
def index(request):
    delNoTitle()
    is_sign_in = isSignIn(request)  #get is signed in

    if request.method == "POST":
        form=PhotoForm(data=request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            temp = Photo.objects.latest('id')
            temp.user = str(request.user)
            temp.save()
            
            return redirect('/')
    else:
        form=PhotoForm() 
    
    photoList = currentPhoto(request)

    return render(request,"pictureApp/index.html", {
        "photo":photoList, 
        "form": form,
        "isSignIn": is_sign_in
        })

# Add Multiple Photos
def addMultiplePhotos(request):
    photoList = []
    if request.method == "POST":
        images = request.FILES.getlist('images')
        for i in images:
            photo = Photo.objects.create(title="NoNameTitle", image=i, user=str(request.user))
            photo.save()

    form = PhotoForm()
    is_sign_in = isSignIn(request)  #get is signed in
    pList = currentPhoto(request)

    for p in pList:
        if p[1].title == "NoNameTitle":
            if p[1].user == str(request.user):
                photoList.append(p)

    return render(request,"pictureApp/multiPhoto.html", {
        "photo":photoList, 
        "form": form,
        "isSignIn": is_sign_in,
        "pageName": 'addMultiplePhotos'
        })

# Add Title Multiple Photos
def titleMultiplePhotos(request):
    photoList = []
    if request.method == "POST":
        _id = request.POST.getlist("multiID")
        _title = request.POST.getlist("multiTitle")
        _size = len(_id)

        for i in range(0,_size):
            _obj = Photo.objects.get(id = eval(_id[i]))
            _obj.title = _title[i]
            _obj.save()
        
        return redirect('/') 

    form = PhotoForm()
    is_sign_in = isSignIn(request)  #get is signed in
    pList = currentPhoto(request)

    for p in pList:
        if p[1].title == "NoNameTitle":
            if p[1].user == str(request.user):
                photoList.append(p)

    return render(request,"pictureApp/multiPhoto.html", {
        "photo":photoList, 
        "form": form,
        "isSignIn": is_sign_in
        })

def deleteAPhoto(request, _id):
    photo_obj = Photo.objects.get(id=eval(_id)) # get photo object by id
    file_path = 'static/photosFolder/' + str(photo_obj.image)   # get file full path
    os.remove(file_path)    # delete file from local folder
    photo_obj.delete()      # delete object data from database

    form = PhotoForm()
    is_sign_in = isSignIn(request)  #get is signed in
    pList = currentPhoto(request)
    photoList = []

    for p in pList:
        if p[1].title == "NoNameTitle":
            if p[1].user == str(request.user):
                photoList.append(p)

    return render(request,"pictureApp/multiPhoto.html", {
        "photo":photoList, 
        "form": form,
        "isSignIn": is_sign_in,
        "pageName": 'addMultiplePhotos'
        })

def deletePhoto(request, _id):
    photo_obj = Photo.objects.get(id=eval(_id)) # get photo object by id
    file_path = 'static/photosFolder/' + str(photo_obj.image)   # get file full path
    os.remove(file_path)    # delete file from local folder
    photo_obj.delete()      # delete object data from database

    return redirect("/") 

def deleteMultiPhoto(request):
   
    if request.method == 'POST':
        id_List = request.POST.getlist('data[]')

        for _id in id_List:
            p_obj = Photo.objects.get(id=eval(_id))
            file_path = 'static/photosFolder/' + str(p_obj.image)   # get file full path
            os.remove(file_path)    # delete file from local folder
            p_obj.delete()

    return redirect('/')

# Persisting Photo title after modification
def persistPhoto(request, _id):
    if request.method == "POST":
        title = request.POST['newTitle']
        photo_obj = Photo.objects.get(id=eval(_id))
        photo_obj.title= title
        photo_obj.save()

    return redirect ("/")

# Search Photo by title provided by user
def searchPhoto(request):
    is_sign_in = isSignIn(request)  #get is signed in
    search_value = None
    form=PhotoForm()
    photoList = []
    obj = Photo.objects.all()

    if request.method == 'POST':
        search_value = request.POST.get('search_input', False)
        search_value = search_value.lower()

        if search_value != None:
            for p in obj:
                temp = []
                if search_value in p.title.lower():
                    if str(request.user) == p.user:
                        temp.append(True)   # Allow rights to edit photos
                        temp.append(p)
                        photoList.append(temp)
                    else:
                        temp.append(False)   # Dont allow to edit photos
                        if p.status == False:    # False means others' user photo is public
                            temp.append(p)
                            photoList.append(temp)
                
            photoList.reverse()
            
    return render(request,"pictureApp/index.html", {
        "isSignIn": is_sign_in,
        "form": form,
        "photo": photoList
    })
        

# change status from Private to Public and ViceVersa
def statusChange(request, _id):
    photo_obj = Photo.objects.get(id = eval(_id))
    if photo_obj.status == True:
        photo_obj.status = False
    else:
        photo_obj.status = True
    photo_obj.save()

    return redirect('/')

# to display only Current User's Private Photos
def userPrivatePhotos(request):
    is_sign_in = isSignIn(request)  #get is signed in
    form=PhotoForm()    
    photoList = []
    obj = Photo.objects.all()

    for p in obj:
        if str(request.user) == p.user:
            temp = []
            if p.status == True:    # True means photos status is Private
                temp.append(True)   # True allow permission to edit
                temp.append(p)
                photoList.append(temp)

    return render(request,"pictureApp/index.html", {
        "photo": photoList, 
        "form": form,
        "isSignIn": is_sign_in
        })

# to display only Current User's Public Photos
def userPublicPhotos(request):
    is_sign_in = isSignIn(request)  #get is signed in
    form=PhotoForm()    
    photoList = []
    obj = Photo.objects.all()

    for p in obj:
        if str(request.user) == p.user:
            temp = []
            if p.status == False:    # False means photos status is Public
                temp.append(True)   # True allow permission to edit
                temp.append(p)
                photoList.append(temp)

    return render(request,"pictureApp/index.html", {
        "photo": photoList, 
        "form": form,
        "isSignIn": is_sign_in
        })

# to display only Current User's All Photos
def userAllPhotos(request):
    is_sign_in = isSignIn(request)  #get is signed in
    form=PhotoForm()    
    photoList = []
    obj = Photo.objects.all()

    for p in obj:
        temp = []
        if str(request.user) == p.user:
            temp.append(True)   # True allow permission to edit
            temp.append(p)
            photoList.append(temp)

    return render(request,"pictureApp/index.html", {
        "photo": photoList, 
        "form": form,
        "isSignIn": is_sign_in
        })

# to display All Public Photo of Current User's and Other Users
def allPublicPhotos(request):
    is_sign_in = isSignIn(request)  #get is signed in
    form=PhotoForm()    
    photoList = []
    obj = Photo.objects.all()

    for p in obj:
        temp = []
        if p.status == False:   # False means status is Public
            if str(request.user) == p.user:
                temp.append(True)   # True allow permission to edit
                temp.append(p)
                photoList.append(temp)
            else:
                temp.append(False)   # False don't grant permission to edit
                temp.append(p)
                photoList.append(temp)

    return render(request,"pictureApp/index.html", {
        "photo": photoList, 
        "form": form,
        "isSignIn": is_sign_in
        })

### Log out View
def logout(request):
    auth.logout(request) # logout
    return redirect('/')


### Login View
def login(request):
    isValidEntry= False
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        user = auth.authenticate(username = username, password = password)

pictureApp/templates/pictureApp/index.html
{% extends 'pictureApp/sample.html' %}

{% block title %}Photo Gallery{% endblock %} 

{% block body %}
    
    {% if not photo %}
        <h1 style="text-align: center; vertical-align: middle; margin-top: 5rem;">
            There Is No Related Picture Available In The Gallery
        </h1>
    {% else %}
    <div class="row" >
        
        {% for p in photo %}
            <div class="col-sm-4"style="padding-top: 50px" >
                <div class="card" >
                    <img src={{p.1.image.url}} alt="pictures" class="img-thumbnail" style="height :231px; width :600px"  >
                    <div class="row mt-3 ml-2 mr-2" style="height:55px">
                        <div class="col-lg-9 " >
                            &nbsp;  
                            {% if p.0 == True %}
                            <input class="check" type="checkbox"  data-id="{{p.1.id}}">
                            {% endif %}
                            <label style="color: red; font-size: 18px;"> &nbsp; {{p.1.title}}</label>
                        </div>

                        <div class="col-lg-3">
                            {% if p.0 %}
                            <div class="row mt-2"  >

                                <div class="col-sm-2" >
                                    <a href="{% url 'pictureApp:statusChange' p.1.id %}">
                                        {% if p.1.status %} 
                                            <button class="btn btn-primary"><i class="fas fa-lock"></i></button>
                                        {% else %}
                                            <button class="btn btn-secondary"><i class="fas fa-lock-open"></i></button>
                                        {% endif %}
                                    </a>
                                    
                                </div>
                                <div class="col-sm-2">
                                    <a >
                                        <button class="btn btn-primary" data-toggle="modal" data-target="#exampleModal-{{p.1.id}}">
                                            <i class="far fa-edit"></i>
                                        </button>
                                    </a>
                                </div>
                                <div class="col-sm-1">
                                    <a href="{% url 'pictureApp:deletePhoto' p.1.id %}">
                                        <button class="btn btn-primary"><i class="fas fa-trash-alt"></i></button>
                                    </a>
                                </div>
                            </div>
                            {% else %}
                            <h5>Not Your Property</h5>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            
  
            <!-- Modal -->
            <div class="modal fade" id="exampleModal-{{p.1.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-sm" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Change Image Title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <form action="{% url 'pictureApp:persistPhoto' p.1.id %}" method="POST">
                            {% csrf_token %}
                            <div class="modal-body">
                                <div>
                                    <img src={{p.1.image.url}} alt="pictures" class="img-thumbnail" style="width: 100%;">
                                </div>
                                <input type="text" value='{{p.1.title}}' name='newTitle'
                                 style="width: 100%; font-size: 18px;"> 
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary" style="font-size: medium;">Save Title</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% endif %}
{% endblock %}

pictureApp/templates/pictureApp/multiPhoto.html
{% extends 'pictureApp/sample.html' %}

{% block title %}Add Multiple Photos{% endblock %} 

{% block body %}
<div tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Adding Photos Title</h5>
            </div>
            <form action="{% url 'pictureApp:titleMultiplePhotos' %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    <!--  -->
                    {% for p in photo %}
                        <!-- Modal -->
                        <!-- <div class="modal fade" tabindex="-1" aria-labelledby="exampleModalLongTitle""> -->
                        <div style = "text-align:center;" role="dialog" tabindex="-1" aria-labelledby="exampleModalLongTitle" >
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 id="photo{{ forloop.counter }}"> 
                                            <input name="multiID" value={{p.1.id}} readonly style="display:none">
                                            <input type="text" name="multiTitle" required size="50" placeholder="Enter Title of Photo {{ forloop.counter }} ">
                                        </h5>
                                        <a href="{% url 'pictureApp:deleteAPhoto' p.1.id %}" data-dismiss="modal" class="btn btn-primary">
                                            <i class="fas fa-trash-alt"></i>
                                        </a>

                                    </div>
                                    <div class="modal-body">
                                        <img src="{{ p.1.image.url }}" name="multiImg" class="img-fluid" alt="Responsive image">
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <!--  -->
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

pictureApp/templates/pictureApp/sample.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="../../static/pictureApp/styles.css">
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <a  href="{% url 'pictureApp:index' %}" style="position: absolute; color:aqua; font-size: larger; padding-left: 20px;"><h1>Photo Gallery</h1></a>           

            {% if isSignIn %}
                <a href="{% url 'pictureApp:logout' %}" style="font-size: medium; position: absolute; right: 20px">
                    <span class="glyphicon glyphicon-user"></span> Logout
                </a>
            {% else %}
                
                <a href="#"  data-toggle="modal" data-target="#loginModal" 
                    style="font-size: medium; position: absolute; right: 20px">
                    {% if isValidEntry %}
                        <span style="color: aqua;">Invalid username OR password</span>
                    {% endif %}
                    <span class="glyphicon glyphicon-log-in"></span> Login
                </a>
            {% endif %}
        </nav> 
        
        <!-- Modal -->
        <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true" style="font-size: 18px;">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">LogIn Page</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" action="{% url 'pictureApp:login' %}">
                            {% csrf_token %}
                            <div class="form-group">
                            <label>Username</label>
                            <input type="text" name="username" class="form-control" id="exampleInputEmail1"
                             aria-describedby="emailHelp" placeholder="Enter Username" style="font-size: 18px;">
                            </div>
                            <div class="form-group">
                            <label>Password</label>
                            <input type="password" name="password" class="form-control" id="exampleInputPassword1"
                             placeholder="Password" style="font-size: 18px;">
                            </div>              
                            <button type="submit" class="btn btn-primary" style="font-size: 14px;" >Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div style="text-align: center;">
            <form action="{% url 'pictureApp:searchPhoto' %}" method="POST">
                {% csrf_token %}
                <div class="input-group rounded" style="width: 50%; margin-left: 25%; margin-bottom: 15px;" >
                    <input type="search" class="form-control rounded" style=" font-size: large;"
                     placeholder="Search" aria-label="Search" aria-describedby="search-addon" name="search_input" />
                    
                    <button class="input-group-text border-0" id="search-addon" type='submit'>
                    <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>
            
            {% if pageName == 'addMultiplePhotos' %}
            <span> 
                <a class="btn btn-primary" href="{% url 'pictureApp:index' %}"
                 style="margin-right: 20px; font-size: 18px; border-radius: 15px;" role="button">
                    Back to Home Page without Saving Photos
                </a>    
            </span>
            {% elif isSignIn %}
            <span>  
                <a class="btn btn-primary btn-font"
                 style="margin-right: 20px; font-size: 18px; border-radius: 15px;"
                  href="{% url 'pictureApp:index' %}" role="button">Home Page</a>
                <button id="displayAdd" style="font-size: 18px;  border-radius: 15px;" data-toggle="modal"
                 data-target="#addSinglePhoto" class="btn btn-primary" type="submit">Add Single Photo</button>
                <button id="displayAdd" style="font-size: 18px; border-radius: 15px;" data-toggle="modal"
                 data-target="#addMultiplePhoto" class="btn btn-primary" type="submit">Add Multiple Photos</button>
                <button id="displayDelete" style="font-size: 18px; border-radius: 15px;" class="btn btn-primary"
                 type="submit">Delete Multiple Photos</button>

                <span class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" style="margin-left: 20px; font-size: 18px; border-radius: 15px;"
                     type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Filter Photo
                    </button>
                    <span class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="font-size: 18px; border-radius: 15px;">
                        <a class="dropdown-item" href="{% url 'pictureApp:userAllPhotos' %}">User All Photos</a>
                        <a class="dropdown-item" href="{% url 'pictureApp:userPrivatePhotos' %}">User Private Photos</a>
                        <a class="dropdown-item" href="{% url 'pictureApp:userPublicPhotos' %}">User Public Photos</a>
                        <a class="dropdown-item" href="{% url 'pictureApp:allPublicPhotos' %}">All Public Photos</a>
                    </span>
                </span>
            </span>
            {% endif %}
            <hr />

            <!-- Modal -->
            <div class="modal fade" id="addSinglePhoto" tabindex="-1" role="dialog"
             aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel"  style="font-size: 18px;">Add Single Photo</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                            <form action="{% url 'pictureApp:index' %}" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input style="width: 100%; height: auto; font-size: 18px; margin-bottom: 5px;"
                                 placeholder="Enter Photo Title" {{form.title}}
                                 {{form.image}}
                                
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-lg btn-success">Upload</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="addMultiplePhoto" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel" style="font-size: 18px;">Add Multiple Photos</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                        <form action="{% url 'pictureApp:addMultiplePhotos' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input required name="images" type="file" multiple class="form-control-file">                       
                            
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-lg btn-success">Upload</button>
                            </div>
                        </form>
                    </div>
                    
                </div>
                </div>
            </div>

        </div>
        

        {% block body %}
        {% endblock %}
        
        <!-- Footer -->
        <div class="bg-info mt-8 "
            style="bottom: 0; width: 100%; color: white; text-align: center; margin-top: 50px;
            height:auto !important; min-height:100%;margin-top: 500px;"> 
  
            <h3 style="color:azure;">Website Developer: Sammar Abbas  -  
            <a href="mailto:mastersagh@hotmail.com" style="color: aqua;">Email : mastersagh@hotmail.com</a></h3>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

        <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
        <script>
            $(document).ready(function(){
                const headerDiv = ['#formDiv'];
                $("#formDiv").hide();
                
                function hideAllFunction (){
                    let i = 0;
                    for (i = 0; i < headerDiv.length; i++){
                        $(headerDiv[i]).hide();
                    }
                }

                // display form div to add a Photo on click
                $("#displayAdd").click(function(){
                    hideAllFunction();
                    $("#formDiv").show();
                });

                // display form div to add a Photo on click
                $("#displayDelete").click(function(){
                    hideAllFunction();
                    
                    var arr = [];
                    $('input.check:checkbox:checked').each(function () {
                        let checkedBox_ids = $(this).attr("data-id");
                        arr.push(checkedBox_ids);
                    });
                    
                    $.ajax({
                        type: 'POST',
                        headers: { "X-CSRFToken": '{{csrf_token}}' },
                            url: 'http://127.0.0.1:8000/deleteMultiPhoto/',
                            data: {data : arr,}, 
                            success: function (data) { location.reload(); },
                            error: function() { location.reload(); 
                        }
                    });
                });
            });
        </script>
    </body>
</html>